import type { Metadata } from "next";
// import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import {
  StyledEngineProvider,
  ThemeProvider,
} from "@mui/material/styles";
import CssBaseline from '@mui/material/CssBaseline';
import { Inter } from "next/font/google";
import "./globals.css";
import theme from "@/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <AppRouterCacheProvider options={{ enableCssLayer: true, key: "css" }}> */}
        <body id="root" className={inter.className}>
          {/* <AppRouterCacheProvider> */}
            <StyledEngineProvider injectFirst>
              <ThemeProvider theme={theme}>
              <CssBaseline />
              {children}
              </ThemeProvider>
            </StyledEngineProvider>
          {/* </AppRouterCacheProvider> */}
        </body>
      {/* </AppRouterCacheProvider> */}
    </html>
  );
}
